name: Run index.js with Yarn & Chrome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Run index.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: yarn start

      - name: Increment version with standard-version
        id: versioning
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          npx standard-version -a -r minor
          echo "version=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Create a Release and add cv.pdf & cv.html
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          name: "Version ${{ steps.versioning.outputs.version }}"
          body: "Automatic generation of CV in PDF and HTML."
          files: |
            CV.*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
